import { useEffect, useMemo, useState } from "react";
import { Check, Clipboard, ExternalLink, Handshake, MapPin, PackageCheck, Send, Truck, X } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { harvestDistricts, lotMessage, matchDemand, type BuyerDemand, type HarvestPlan, validateDemand, validatePlan } from "@/lib/harvest-market";

const today = () => new Date().toISOString().slice(0, 10);
const defaultPlan = (): HarvestPlan => ({ district: "Rangpur", readyDate: today(), quantityKg: 0, transportPerKg: 0 });
const emptyDemand = (): BuyerDemand => ({ id: crypto.randomUUID(), buyer: "", district: "Rangpur", from: today(), to: today(), minKg: 0, maxKg: 0, offeredPerKg: 0, buyerCollects: false, payment: "" });
type Saved = { plan: HarvestPlan; demands: BuyerDemand[] };

export default function HarvestMarket({ storageKey }: { storageKey: string }) {
  const { language } = useLanguage(); const bn = language === "bn";
  const key = `alusathi-harvest-market-v1-${storageKey}`;
  const [plan, setPlan] = useState<HarvestPlan>(defaultPlan);
  const [demands, setDemands] = useState<BuyerDemand[]>([]);
  const [draft, setDraft] = useState<BuyerDemand>(emptyDemand);
  const [showDemand, setShowDemand] = useState(false);
  const [message, setMessage] = useState("");
  const t = (bangla: string, english: string) => bn ? bangla : english;
  const money = (n: number) => `৳${n.toLocaleString(bn ? "bn-BD" : "en-BD", { maximumFractionDigits: 2 })}`;
  useEffect(() => {
    try {
      const saved = JSON.parse(localStorage.getItem(key) || "null") as Saved | null;
      if (saved && validatePlan(saved.plan) && Array.isArray(saved.demands)) { setPlan(saved.plan); setDemands(saved.demands.filter(validateDemand)); }
    } catch { /* Invalid local data is ignored. */ }
  }, [key]);
  useEffect(() => {
    try { localStorage.setItem(key, JSON.stringify({ plan, demands })); } catch { /* The feature remains usable without storage. */ }
  }, [key, plan, demands]);
  const matches = useMemo(() => demands.map(demand => ({ demand, result: matchDemand(plan, demand) })).filter((item): item is { demand: BuyerDemand; result: NonNullable<ReturnType<typeof matchDemand>> } => Boolean(item.result)).sort((a, b) => b.result.score - a.result.score || b.result.netPerKg - a.result.netPerKg), [plan, demands]);
  function updatePlan(key: keyof HarvestPlan, value: string) { setPlan(previous => ({ ...previous, [key]: key === "district" || key === "readyDate" ? value : Number(value) })); }
  function updateDraft(key: keyof BuyerDemand, value: string | boolean) { setDraft(previous => ({ ...previous, [key]: ["buyer", "district", "from", "to", "payment"].includes(key) ? String(value) : key === "buyerCollects" ? Boolean(value) : Number(value) } as BuyerDemand)); }
  async function share() {
    if (!validatePlan(plan)) { setMessage(t("আগে তারিখ, পরিমাণ ও গাড়িভাড়া ঠিকভাবে দিন।", "Enter a valid date, quantity and transport estimate first.")); return; }
    const text = lotMessage(plan);
    try {
      if (navigator.share) await navigator.share({ title: "AluSathi harvest-ready lot", text });
      else { await navigator.clipboard.writeText(text); setMessage(t("বিক্রির তথ্য কপি হয়েছে।", "Lot details copied.")); }
    } catch { setMessage(t("শেয়ার করা হয়নি।", "Lot details were not shared.")); }
  }
  function addDemand(event: React.FormEvent) {
    event.preventDefault();
    if (!validateDemand(draft)) { setMessage(t("ক্রেতার সব তথ্য ঠিকভাবে দিন।", "Enter all buyer-request details correctly.")); return; }
    setDemands(previous => [draft, ...previous]); setDraft(emptyDemand()); setShowDemand(false); setMessage(t("ক্রেতার চাহিদা এই ফোনে যোগ হয়েছে।", "Buyer request saved on this device."));
  }
  return <section id="harvest-market" className="app-shell scroll-mt-24 py-12">
    <div className="section-heading"><div><p className="section-kicker"><Handshake size={16} />{t("বিক্রির প্রস্তুতি", "Sell with a plan")}</p><h2>{t("আলু প্রস্তুত হলে ক্রেতার চাহিদার সঙ্গে মিলিয়ে দেখুন", "Match harvest readiness to buyer demand")}</h2><p>{t("তারিখ, পরিমাণ, পরিবহন ও পাওয়ার টাকা একসঙ্গে দেখুন।", "Bring harvest date, quantity, transport and take-home money into one view.")}</p></div></div>
    <div className="market-trust" role="status"><PackageCheck size={20} /><div><strong>{t("এখনো কোনো লাইভ ক্রেতা-চাহিদা যুক্ত নেই", "No live buyer-demand feed is connected yet")}</strong><p>{t("নিচে ফোনে পাওয়া আসল ক্রেতার তথ্য লিখলে মিল দেখা যাবে। এটি প্রকাশ্য বাজার নয়; তথ্যটি শুধু এই ফোনে থাকবে।", "Enter a real buyer request received by phone below to compare it. This is not a public marketplace; information stays on this device.")}</p></div></div>
    <div className="market-grid">
      <form className="harvest-card tool-form" onSubmit={event => { event.preventDefault(); setMessage(validatePlan(plan) ? t("ফসল প্রস্তুতির তথ্য সেভ হয়েছে।", "Harvest readiness saved.") : t("সব তথ্য ঠিকভাবে দিন।", "Enter all details correctly.")); }}><h3>{t("আমার আলু", "My harvest")}</h3><label>{t("কোথায় আলু আছে?", "Potato district")}<select value={plan.district} onChange={e => updatePlan("district", e.target.value)}>{harvestDistricts.map(district => <option key={district}>{district}</option>)}</select></label><label>{t("কবে আলু প্রস্তুত হবে?", "Expected ready date")}<input type="date" min={today()} max="2100-12-31" value={plan.readyDate} onChange={e => updatePlan("readyDate", e.target.value)} /></label><label>{t("কত আলু বিক্রি করতে পারবেন? (কেজি)", "Available to sell (kg)")}<input type="number" min="1" max="10000000" step="1" inputMode="decimal" value={plan.quantityKg || ""} onChange={e => updatePlan("quantityKg", e.target.value)} /></label><label>{t("ক্রেতার কাছে পাঠাতে আনুমানিক গাড়িভাড়া (টাকা/কেজি)", "Estimated transport to buyer (BDT/kg)")}<input type="number" min="0" max="100000" step="any" inputMode="decimal" value={plan.transportPerKg || ""} onChange={e => updatePlan("transportPerKg", e.target.value)} /></label><button className="secondary-main"><Check size={18} />{t("প্রস্তুতির তথ্য রাখুন", "Save readiness")}</button><button type="button" className="text-button market-share" onClick={share}><Send size={16} />{t("ক্রেতাকে তথ্য পাঠান", "Share lot with a buyer")}</button></form>
      <div className="harvest-card"><h3>{t("ক্রেতার চাহিদা", "Buyer demand")}</h3><p>{t("ক্রেতা ফোনে যা বলেছেন, তা লিখুন। নাম, তারিখ, পরিমাণ, দর ও পরিবহনের দায়িত্ব না জেনে কোনো মিলকে নিশ্চিত বিক্রি ভাববেন না।", "Record what a buyer said by phone. A match is not a confirmed sale until name, dates, quantity, price and transport responsibility are confirmed.")}</p>{!showDemand ? <button className="secondary-main" onClick={() => setShowDemand(true)}><Handshake size={18} />{t("আসল ক্রেতার চাহিদা লিখুন", "Record a real buyer request")}</button> : <form className="tool-form demand-form" onSubmit={addDemand}><label>{t("ক্রেতা/ব্যবসার নাম", "Buyer or business name")}<input required maxLength={100} value={draft.buyer} onChange={e => updateDraft("buyer", e.target.value)} /></label><div className="tool-columns"><label>{t("ডেলিভারি জেলা", "Delivery district")}<select value={draft.district} onChange={e => updateDraft("district", e.target.value)}>{harvestDistricts.map(district => <option key={district}>{district}</option>)}</select></label><label>{t("পেমেন্টের কথা", "Payment terms")}<input required maxLength={100} placeholder={t("যেমন: মাল বুঝে সেদিন", "e.g. same-day after delivery")} value={draft.payment} onChange={e => updateDraft("payment", e.target.value)} /></label></div><div className="tool-columns"><label>{t("নেওয়া শুরু", "Delivery from")}<input required type="date" min={today()} max="2100-12-31" value={draft.from} onChange={e => updateDraft("from", e.target.value)} /></label><label>{t("নেওয়া শেষ", "Delivery until")}<input required type="date" min={draft.from || today()} max="2100-12-31" value={draft.to} onChange={e => updateDraft("to", e.target.value)} /></label></div><div className="tool-columns"><label>{t("সর্বনিম্ন (কেজি)", "Minimum (kg)")}<input required type="number" min="1" max="10000000" step="1" value={draft.minKg || ""} onChange={e => updateDraft("minKg", e.target.value)} /></label><label>{t("সর্বোচ্চ (কেজি)", "Maximum (kg)")}<input required type="number" min={draft.minKg || 1} max="10000000" step="1" value={draft.maxKg || ""} onChange={e => updateDraft("maxKg", e.target.value)} /></label></div><label>{t("প্রস্তাবিত দর (টাকা/কেজি)", "Offered price (BDT/kg)")}<input required type="number" min="0" max="100000" step="any" inputMode="decimal" value={draft.offeredPerKg || ""} onChange={e => updateDraft("offeredPerKg", e.target.value)} /></label><label className="checkbox-label"><input type="checkbox" checked={draft.buyerCollects} onChange={e => updateDraft("buyerCollects", e.target.checked)} />{t("ক্রেতা নিজে আলু নেবেন; আমার গাড়িভাড়া লাগবে না", "Buyer will collect; my transport estimate does not apply")}</label><div className="report-actions"><button className="secondary-main">{t("চাহিদা যোগ করুন", "Add buyer request")}</button><button type="button" className="text-button" onClick={() => { setShowDemand(false); setDraft(emptyDemand()); }}>{t("বাদ দিন", "Cancel")}</button></div></form>}</div>
    </div>
    {message && <p className="tool-notice" role="status">{message}</p>}
    <div className="match-board"><div className="section-heading"><div><p className="section-kicker"><Truck size={16} />{t("সম্ভাব্য মিল", "Possible matches")}</p><h3>{t("ক্রেতার চাহিদার সঙ্গে তুলনা", "Compare against buyer requirements")}</h3></div></div>{matches.length ? <div className="match-list">{matches.map(({ demand, result }) => <article className={`match-card score-${result.score}`} key={demand.id}><div className="match-card-head"><div><p>{demand.buyer}</p><h4>{result.score === 3 ? t("৩টি তথ্যই মিলে গেছে", "All three requirements match") : result.score === 2 ? t("কথা বলে মিলিয়ে নিন", "One point needs discussion") : t("এখনো ভালো মিল নয়", "Not a strong match yet")}</h4></div><button className="text-button" aria-label={t("চাহিদা মুছুন", "Delete request")} onClick={() => setDemands(previous => previous.filter(item => item.id !== demand.id))}><X size={17} /></button></div><div className="match-facts"><span className={result.dateMatch ? "match-yes" : "match-no"}>{result.dateMatch ? <Check /> : <X />}{t("তারিখ", "Date")}: {demand.from}–{demand.to}</span><span className={result.quantityMatch ? "match-yes" : "match-no"}>{result.quantityMatch ? <Check /> : <X />}{t("পরিমাণ", "Quantity")}: {demand.minKg.toLocaleString()}–{demand.maxKg.toLocaleString()} kg</span><span className={result.districtMatch ? "match-yes" : "match-no"}>{result.districtMatch ? <Check /> : <MapPin />}{t("ডেলিভারি", "Delivery")}: {demand.district}</span></div><dl><div><dt>{t("দর", "Offered price")}</dt><dd>{money(demand.offeredPerKg)}/{t("কেজি", "kg")}</dd></div><div><dt>{t("আনুমানিক হাতে", "Estimated take-home")}</dt><dd>{money(result.netPerKg)}/{t("কেজি", "kg")}</dd></div><div><dt>{t("মোট আনুমানিক", "Estimated total")}</dt><dd>{money(result.estimatedNet)}</dd></div></dl><p>{demand.buyerCollects ? t("ক্রেতা নিজে নেবেন বলেছেন।", "Buyer said they will collect.") : t(`আপনার দেওয়া গাড়িভাড়া ${money(plan.transportPerKg)}/কেজি বাদ দেওয়া হয়েছে।`, `Your transport estimate of ${money(plan.transportPerKg)}/kg was deducted.`)} {t(`পেমেন্ট: ${demand.payment}`, `Payment: ${demand.payment}`)}</p><small>{t("এটি দর-কষাকষির হিসাব, বিক্রির নিশ্চয়তা নয়। ওজন, গ্রেড, কাটতি, টাকা দেওয়ার সময় ও রসিদ লিখিতভাবে মিলিয়ে নিন।", "This supports negotiation, not a guaranteed sale. Confirm weight, grade, deductions, payment time and a receipt in writing.")}</small></article>)}</div> : <div className="market-empty"><Clipboard size={30} /><h4>{t("এখনো কোনো ক্রেতার চাহিদা যোগ হয়নি", "No buyer requests recorded yet")}</h4><p>{t("ফোনে পাওয়া আসল চাহিদা লিখুন। এরপর তারিখ, পরিমাণ ও ডেলিভারির মিল দেখা যাবে।", "Record a real request received by phone. Then the app will check the date, quantity and delivery fit.")}</p></div>}</div>
    <div className="partner-links"><strong>{t("ব্যবসার সঙ্গে কথা শুরু করুন", "Start a conversation with businesses")}</strong><span>{t("আলুসাথী তাদের দরের তথ্য পায় না। লিংকে গিয়ে নিজের আলুর তথ্য দিন বা প্রকল্পের পাইলট পার্টনার হন।", "AluSathi does not receive their pricing. Use these channels to submit your lot, or make them pilot partners.")}</span><div><a href="https://www.ifarmer.asia/" target="_blank" rel="noopener noreferrer">iFarmer <ExternalLink size={14} /></a><a href="https://fashol.com/solutions/wholesalers" target="_blank" rel="noopener noreferrer">Fashol <ExternalLink size={14} /></a><a href="https://sadai.gov.bd/" target="_blank" rel="noopener noreferrer">Sadai <ExternalLink size={14} /></a></div></div>
  </section>;
}
